version: "3.7"
services: 
  db:
    image: mysql:5.7
    container_name: website-db
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: "${PASSWORD_ROOT_MYSQL}"
    ports: 
      - "${PORT_MYSQL}:3306"
    volumes: 
      - ./mysql-data/:/var/lib/mysql
    networks:
      - baubyte
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: website-pma
    restart: unless-stopped
    ports:
      - "${PORT_PHPMYADMIN}:80"
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: website-db
      PMA_PORT: 3306
    networks:
      - baubyte
    depends_on: 
      - db
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        uid: 1000
    image: website-dev
    container_name: website-web
    restart: unless-stopped
    ports: 
      - "${PORT_APACHE_WEB}:80"
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes: 
      - ./website-src/:/var/www
      - ./website-src/public:/var/www/html
    networks:
      - baubyte
    depends_on: 
      - db
networks:
 baubyte:
    driver: bridge
volumes: 
  mysql-data:
  website-src: